services:
  migrate:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
    command:
      [
        "sh",
        "-lc",
        "apps/api/node_modules/.bin/prisma --schema apps/api/prisma/schema.prisma migrate deploy && node -r ./apps/api/node_modules/ts-node/register apps/api/prisma/seed.ts",
      ]
    networks:
      - web

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      APP_BASE_URL: https://opaa.devmais.com
      API_BASE_PATH: /api
      COOKIE_SECURE: "true"
      PORT: 3000
    depends_on:
      migrate:
        condition: service_completed_successfully
    networks:
      - web

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      args:
        VITE_API_BASE_URL: https://opaa.devmais.com/api
    ports:
      - "3000:80"
    depends_on:
      - api
    networks:
      - web

networks:
  web:
    external: true
