services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: opaa
      POSTGRES_USER: opaa
      POSTGRES_PASSWORD: opaa
    ports:
      - "55432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "8025:8025"
      - "1025:1025"

volumes:
  postgres_data:
